resource_group_name                         = "nprd-dev"
resource_group_location                     = "EastUS"
storage_account_name                        = "nprddevsa"
storage_account_tier                        = "Standard"
private_link_service_name                   = "nprd-dev-pls"
primary_private_ip_addr                     = "10.2.0.4"
private_endpoint_name                       = "nprd-dev-pe"
vnet_name                                   = "nprd-dev-vnet"
vnet_address_space                          = "10.2.0.0/16"
subnet_name                                 = "nprd-dev-subnet"
subnet_address_prefixes                     = "10.2.0.0/24"
nat_gateway_name                            = "nprd-dev-nat"
lb_name                                     = "nprd-dev-lb"
lb_location                                 = "EastUS"
load_balancer_public_ip_name                = "nprd-dev-lbip"

